=== L2JMobius/L2Jmobius_Interlude/L2J_Mobius_CT_0_Interlude/dist/game/data/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="set">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="val" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" name="cond">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" name="and">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="player">
														<xs:complexType>
															<xs:attribute name="castle" type="xs:byte" use="optional" />
															<xs:attribute name="pledgeClass" type="xs:byte" use="optional" />
															<xs:attribute name="races" type="xs:string" use="optional" />
															<xs:attribute name="clanHall" type="xs:byte" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element minOccurs="0" name="player">
											<xs:complexType>
												<xs:attribute name="races" type="xs:string" use="optional" />
												<xs:attribute name="isPvpFlagged" type="xs:boolean" use="optional" />
												<xs:attribute name="categoryType" type="xs:string" use="optional" />
												<xs:attribute name="isHero" type="xs:boolean" use="optional" />
												<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
												<xs:attribute name="pkCount" type="xs:unsignedByte" use="optional" />
												<xs:attribute name="pledgeClass" type="xs:unsignedByte" use="optional" />
												<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="msgId" type="xs:unsignedShort" use="required" />
									<xs:attribute name="addName" type="xs:unsignedByte" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" name="for">
								<xs:complexType>
									<xs:sequence>
										<xs:choice maxOccurs="unbounded">
											<xs:element maxOccurs="unbounded" name="set">
												<xs:complexType>
													<xs:attribute name="stat" type="xs:string" use="required" />
													<xs:attribute name="val" type="xs:unsignedShort" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="add">
												<xs:complexType>
													<xs:attribute name="stat" type="xs:string" use="required" />
													<xs:attribute name="val" type="xs:decimal" use="required" />
													<xs:attribute name="order" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
											<xs:element name="sub">
												<xs:complexType>
													<xs:attribute name="stat" type="xs:string" use="required" />
													<xs:attribute name="val" type="xs:unsignedByte" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element name="enchant">
												<xs:complexType>
													<xs:attribute name="stat" type="xs:string" use="required" />
													<xs:attribute name="val" type="xs:unsignedByte" use="required" />
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedShort" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== L2JMobius/L2Jmobius_Interlude/L2J_Mobius_CT_0_Interlude/dist/game/data/stats/items/09200-09299.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="9200" type="Armor" name="Shadow Item - Jester Hat - Firework">
		<!-- A festive, shadow-type jester hat with 2 points. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="icon" val="icon.accessory_jester_cap_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="equip_reuse_delay" val="30" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="item_skill" val="3266-1" /> <!-- Large Fireworks Ability -->
		<set name="duration" val="360" />
		<set name="useSkillDisTime" val="5" />
	</item>
	<item id="9201" type="Armor" name="Shadow Item - Wizard Hat - Firework">
		<!-- A shadow-type wizard hat with a wide brim and bent tip. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="icon" val="icon.accessory_magic_cap_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="equip_reuse_delay" val="30" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="item_skill" val="3266-1" /> <!-- Large Fireworks Ability -->
		<set name="duration" val="360" />
		<set name="useSkillDisTime" val="5" />
	</item>
	<item id="9202" type="Armor" name="Shadow Item - Dapper Cap - Firework">
		<!-- A shadow-type hair accessory with a visor. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="icon" val="icon.accessory_dandy_cap_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="equip_reuse_delay" val="30" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="item_skill" val="3266-1" /> <!-- Large Fireworks Ability -->
		<set name="duration" val="360" />
		<set name="useSkillDisTime" val="5" />
	</item>
	<item id="9203" type="Armor" name="Shadow Item - Romantic Chapeau - Firework">
		<!-- A shadow-type hair accessory adorned with feathers. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="icon" val="icon.accessory_romantic_chaperon_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="equip_reuse_delay" val="30" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="item_skill" val="3266-1" /> <!-- Large Fireworks Ability -->
		<set name="duration" val="360" />
		<set name="useSkillDisTime" val="5" />
	</item>
	<item id="9204" type="Armor" name="Shadow Item - Iron Circlet - Firework">
		<!-- A shadow-type hair accessory made of iron. Uses 2 hair accessory slots. An event hair accessory that grants a magical effect. This item cannot be exchanged, dropped, or sold. -->
		<set name="icon" val="icon.accessory_iron_circlet_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="equip_reuse_delay" val="30" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="item_skill" val="3266-1" /> <!-- Large Fireworks Ability -->
		<set name="duration" val="360" />
		<set name="useSkillDisTime" val="5" />
	</item>
	<item id="9205" type="EtcItem" name="Alchemist's Chest Key">
		<!-- A key to open an Alchemist's Treasure Chest. For use in events only -->
		<set name="icon" val="icon.etc_old_key_i02" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="10" />
		<set name="is_stackable" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="2322-1" /> <!-- Chest Key - For Events Only -->
	</item>
	<item id="9206" type="EtcItem" name="Greater Healing Potion (Event)">
		<!-- A magical potion that quickly restores HP. Its effect lasts for 15 seconds. Designed for use in events only. -->
		<set name="icon" val="icon.etc_reagent_white_i00" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="etcitem_type" val="POTION" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="5" />
		<set name="reuse_delay" val="10000" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="2037-1" /> <!-- Greater Healing Potion -->
		<set name="for_npc" val="true" />
	</item>
	<item id="9207" type="EtcItem" name="Quick Healing Potion (Event)">
		<!-- A magical potion that quickly restores HP. Its effect is temporary. Designed for use in events only. -->
		<set name="icon" val="icon.etc_potion_gold_i00" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="etcitem_type" val="POTION" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="LIQUID" />
		<set name="weight" val="5" />
		<set name="reuse_delay" val="500" />
		<set name="is_stackable" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="handler" val="ItemSkills" />
		<set name="item_skill" val="2038-1" /> <!-- Quick Healing Potion -->
		<set name="for_npc" val="true" />
	</item>
	<item id="9208" type="Armor" name="Phantom Mask (Event)">
		<!-- A feathered hair accessory. This item cannot be exchanged or dropped. -->
		<set name="icon" val="icon.accessary_mask_of_chaotic_i00" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
	</item>
</list>
